spring.datasource.url=jdbc:postgresql://localhost:5432/selfos
spring.datasource.username=postgres
spring.datasource.password=pass1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8080

application.security.jwt.secret-key=MyVeryLongSecretKeyForSelfOSJwtAuthentication2026SuperSecureKey123456

application.security.jwt.access-token-expiration=3600000

application.security.jwt.refresh-token-expiration=604800000
