apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfos-frontend
  namespace: selfos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfos-frontend
  template:
    metadata:
      labels:
        app: selfos-frontend
    spec:
      containers:
      - name: frontend
        image: selfos-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"

        limits:
          cpu: "200m"
          memory: "256Mi"

      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10

      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5