apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfos-frontend
  namespace: selfos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfos-frontend
  template:
    metadata:
      labels:
        app: selfos-frontend
    spec:
      containers:
      - name: frontend
        image: selfos-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80