apiVersion: v1
kind: Secret
metadata:
  name: selfos-secret
  namespace: selfos

type: Opaque

data:
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: TXlWZXJ5TG9uZ1NlY3JldEtleUZvclNlbGZPU0p3dEF1dGhlbnRpY2F0aW9uMjAyNlN1cGVyU2VjdXJlS2V5MTIzNDU2
